apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: "bXlwYXNz"       # mypass       в MySQL буде створений root з паролем "mypass" 
  MYSQL_USER: "bW92aWVzdXNlcg=="        # moviesuser   -- " --   moviesuser з паролем ThePassword
  MYSQL_PASSWORD: "VGhlUGFzc3dvcmQ="    #ThePassword
