image:
  repository: dmirina
  name: microservices-service                   # образ з докера
  tag: 3.2                                      # версія образа

migrations:
  image:
    repository: dmirina
    name: migrations
    tag: "2.1"
  config:
    MYSQL_URL: "mysql://root:mypass@tcp(mysql:3306)/cinema?tls=false"
    VERSION: "20230101"

configs:
  DB_HOST: "mysql:3306"
  DB_NAME: "cinema"

secrets:
  DB_USERNAME: "cm9vdA==" #root
  DB_PASSWORD: "bXlwYXNz" #mypass

service:
  ports:
    - name: http
      port: 80                           # порт по якому можна звератись до сервісу
      containerPort: 8080                # порт контейнера

ingress:
  path: /api
  port: http